task:
  freebsd_instance:
    matrix:
      - image_family: freebsd-11-4-snap
      - image_family: freebsd-13-0-snap
  deps_script:
    - sed -i.bak -e 's/quarterly/latest/' /etc/pkg/FreeBSD.conf
    - pkg install -y meson pkgconf dbus glib libepoll-shim libudev-devd vulkan-loader vulkan-headers gstreamer1 gstreamer1-plugins libinotify
    - sysrc dbus_enable=YES
    - service dbus restart
  build_script:
    - mkdir build
    - cd build
    - meson setup -Dalsa=disabled -Dpipewire-alsa=disabled -Dbluez5=disabled -Djack=disabled -Dpipewire-jack=disabled -Dpipewire-pulseaudio=disabled -Dv4l2=disabled -Dsystemd=disabled ..
    - ninja
  test_script:
    - cd build
    - ninja test
